### ISSUE TITLE
Daisy Chain Plugins

### ISSUE THREAD

**Issue by BBloggsbott** [BBloggsbott/ready-to-serv#12]
Allow users to Daisy Chain result of one plugin as input to another.

**Comment by BBloggsbott** [comment]
Proposed plugin config schema for daisy-chaining plugins
```yaml
version: 2.0
jars:
    - id: sum
      jarfile: helloworld.jar
      method: com.bbloggsbott.helloworld.HelloWorld.getSum
      args:
          - name: a
            type: int
            requestParam: true
          - name: b
            type: int
            requestParam: true
      returns: int
    - id: sqrt
      jarfile: helloworld.jar
      method: com.bbloggsbott.helloworld.HelloWorld.getSqrt
      args:
          - name: a
            type: int

chains:
    - name: sum_and_sqrt
      steps:
          - id: sum
          - id: sqrt

endpoints:
    - sum_and_sqrt: /sum_sqrt
    - sum: /sum
    - sqrt: /sqrt
```

@jaikanthjay46 , Thoughts?
